name: Deploy learnx-tasks to Ark

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4


      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.14.0
          run_install: false

      - name: Install dependencies
        run: pnpm install

      # docker setup - part 1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # docker setup - part 2
      - name: Login to Ark registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      # - name: Login to Ark registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ secrets.REGISTRY_URL }}
      #     username: ${{ secrets.REGISTRY_USERNAME }}
      #     password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: ðŸš€ Deploy Tasks
        env:
          TRIGGER_ACCESS_TOKEN: ${{ secrets.TRIGGER_ACCESS_TOKEN }}
          TRIGGER_API_URL: ${{ secrets.TRIGGER_API_URL }}
          REGISTRY_URL: ghcr.io
        run: |
          # Deploy to staging environment
          pnpm dlx trigger.dev@latest deploy --push --registry "ghcr.io/moonshotedx" --env staging

          # Deploy to production environment
          pnpm dlx trigger.dev@latest deploy --push --registry "ghcr.io/moonshotedx" --env prod
